server:
  port: 31001
spring:
  application:
    name: xc_service_manage_cms
  freemarker:
      cache: false #关闭模板缓存，方便测试
      settings:
      #检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便进行模板测试
          template_update_delay: 0
  rabbitmq:
    host: 192.168.203.22
    port: 5672
    username: user
    password: user
    virtual-host:  /
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017
      database: xc_cms
xuecheng:
    mq: #cms客户端监控的队列名称（不同的客户端监控的队列不能重复）
       queue: queue_cms_postpage_01
       routingKey: 5a751fab6abb5044e0d19ea1 #此routingKey为门户站点ID